# Generated by Django 3.1 on 2020-08-31 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Room',
                'db_table': 'room',
            },
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('level', models.CharField(choices=[('1', 'Lớp 1'), ('2', 'Lớp 2'), ('3', 'Lớp 3'), ('4', 'Lớp 4'), ('5', 'Lớp 5'), ('6', 'Lớp 6'), ('7', 'Lớp 7'), ('8', 'Lớp 8'), ('9', 'Lớp 9'), ('10', 'Lớp 10'), ('11', 'Lớp 11'), ('12', 'Lớp 12'), ('13', 'Sinh viên'), ('14', 'Đang đi làm')], default='14', max_length=255)),
            ],
            options={
                'verbose_name': 'Subjects',
                'verbose_name_plural': 'Subjects',
                'db_table': 'subjects',
            },
        ),
        migrations.CreateModel(
            name='TimeSubjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('1', 'Thứ 2'), ('2', 'Thứ 3'), ('3', 'Thứ 4'), ('4', 'Thứ 5'), ('5', 'Thứ 6'), ('6', 'Thứ 7'), ('7', 'Chủ nhật')], default='1', max_length=255)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.room')),
                ('subjects', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.subjects')),
                ('time', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.time_of_day')),
            ],
            options={
                'verbose_name': 'TimeSubjects',
                'verbose_name_plural': 'TimeSubjects',
                'db_table': 'time_and_subjects',
            },
        ),
        migrations.CreateModel(
            name='ScheduleTeach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.room')),
                ('schedule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.timesubjects')),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.subscribers')),
            ],
            options={
                'verbose_name': 'ScheduleTeach',
                'verbose_name_plural': 'ScheduleTeach',
                'db_table': 'schedule_teach',
            },
        ),
    ]
