# Generated by Django 3.1 on 2020-08-31 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_room_scheduleteach_subjects_timesubjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='backend.subscribers')),
                ('level', models.CharField(choices=[('1', 'Lớp 1'), ('2', 'Lớp 2'), ('3', 'Lớp 3'), ('4', 'Lớp 4'), ('5', 'Lớp 5'), ('6', 'Lớp 6'), ('7', 'Lớp 7'), ('8', 'Lớp 8'), ('9', 'Lớp 9'), ('10', 'Lớp 10'), ('11', 'Lớp 11'), ('12', 'Lớp 12'), ('13', 'Sinh viên'), ('14', 'Đang đi làm')], default='14', max_length=255)),
                ('created_at', models.DateTimeField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('schedule_registere', models.ManyToManyField(blank=True, to='backend.TimeSubjects')),
                ('subjects_teach', models.ManyToManyField(blank=True, to='backend.Subjects')),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teacher',
                'db_table': 'teacher',
            },
        ),
    ]
