# Generated by Django 3.1 on 2020-10-20 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribers',
            old_name='deleted_at',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='schedulelearn',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='timesubjects',
            name='subjects',
        ),
        migrations.AddField(
            model_name='schedulelearn',
            name='subject',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.subjects'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedulelearn',
            name='time',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.timesubjects'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjects',
            name='time',
            field=models.ManyToManyField(blank=True, related_name='list_timesubject', to='backend.TimeSubjects'),
        ),
        migrations.AddField(
            model_name='timesubjects',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngay ket thuc'),
        ),
        migrations.AddField(
            model_name='timesubjects',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngay bat dau'),
        ),
        migrations.AddField(
            model_name='timesubjects',
            name='teacher',
            field=models.ManyToManyField(blank=True, related_name='list_subscribers', to='backend.Subscribers'),
        ),
        migrations.AlterField(
            model_name='subscribers',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='subscribers',
            name='position',
            field=models.CharField(max_length=255),
        ),
        migrations.RemoveField(
            model_name='timesubjects',
            name='room',
        ),
        migrations.AddField(
            model_name='timesubjects',
            name='room',
            field=models.ManyToManyField(blank=True, related_name='list_room', to='backend.Room'),
        ),
        migrations.AlterField(
            model_name='timesubjects',
            name='time',
            field=models.CharField(choices=[('1', '7h - 9h'), ('2', '9h - 11h'), ('3', '14h - 16h'), ('4', '16h - 18h'), ('5', '18h - 20h'), ('6', '17h - 19h'), ('7', '19h - 21h'), ('8', '18h - 19h')], default='1', max_length=255),
        ),
        migrations.DeleteModel(
            name='ScheduleTeach',
        ),
        migrations.DeleteModel(
            name='Time_of_day',
        ),
    ]
