# Generated by Django 3.1 on 2020-12-21 03:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0009_auto_20201021_0909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulelearn',
            name='student',
        ),
        migrations.AddField(
            model_name='schedulelearn',
            name='student',
            field=models.ManyToManyField(blank=True, related_name='employees', to=settings.AUTH_USER_MODEL),
        ),
    ]
