# Generated by Django 3.1 on 2020-12-21 03:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0010_auto_20201221_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulelearn',
            name='student',
            field=models.ManyToManyField(blank=True, related_name='students', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TKB',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='backend.subscribers')),
                ('schedule_learn', models.ManyToManyField(blank=True, related_name='schedule', to='backend.ScheduleLearn')),
            ],
            options={
                'verbose_name': 'TKB',
                'verbose_name_plural': 'TKB',
                'db_table': 'TKB',
            },
        ),
    ]
