# Generated by Django 3.1 on 2020-12-21 04:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0012_auto_20201221_0351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribers',
            name='id',
        ),
        migrations.AlterField(
            model_name='subscribers',
            name='uid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
