# Generated by Django 3.1 on 2020-12-21 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_auto_20201221_0412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulelearn',
            name='time',
        ),
    ]
