# Generated by Django 3.1 on 2020-12-23 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_auto_20201221_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribers',
            name='gender',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Not declared'), (1, 'Male'), (2, 'Female')], default=0, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='subscribers',
            name='id_selfie',
            field=models.ImageField(blank=True, null=True, upload_to='media/profile', verbose_name='Selfie'),
        ),
    ]
