# Generated by Django 3.1 on 2020-12-24 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_auto_20201223_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribers',
            name='gender',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Khác'), (1, 'Nam'), (2, 'Nữ')], default=0, verbose_name='Gender'),
        ),
    ]
