# Generated by Django 3.1 on 2020-12-24 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_auto_20201224_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulelearn',
            name='student',
            field=models.ManyToManyField(blank=True, related_name='students', to='backend.Subscribers'),
        ),
        migrations.AlterField(
            model_name='subscribers',
            name='id_selfie',
            field=models.ImageField(default='media/profile/None/no-img.jpg', upload_to='media/profile', verbose_name='Selfie'),
        ),
    ]
