# Generated by Django 3.1 on 2021-01-07 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_auto_20210106_0351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulelearn',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='schedulelearn',
            name='time',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='time',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='timesubjects',
            name='room',
        ),
        migrations.RemoveField(
            model_name='timesubjects',
            name='teacher',
        ),
        migrations.AddField(
            model_name='teacher',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tkb',
            name='schedule_learn',
            field=models.ManyToManyField(blank=True, related_name='tkb_schedule', to='backend.ScheduleLearn'),
        ),
        migrations.CreateModel(
            name='ScheduleTeach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groubId', models.CharField(max_length=255)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.room')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.subjects')),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.subscribers')),
                ('time', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.timesubjects')),
            ],
            options={
                'verbose_name': 'ScheduleTeach',
                'verbose_name_plural': 'ScheduleTeach',
                'db_table': 'schedule_teach',
            },
        ),
    ]
