# Generated by Django 3.1 on 2021-01-07 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_auto_20210107_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleteach',
            name='teacher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.teacher'),
        ),
    ]
