# Generated by Django 3.1 on 2021-01-11 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_auto_20210107_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleteach',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.teacher'),
        ),
    ]
